//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {
/// <summary>Rectangular measurement field with individual radiation parameters.</summary>
/// Once added via the IRImager the setters will no loner affect the processing of the field because the IRImager creates an
/// internal copy of the field.

public class MeasurementField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MeasurementField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MeasurementField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MeasurementField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MeasurementField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otcsdkPINVOKE.delete_MeasurementField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  ///  Constructor.
  public MeasurementField() : this(otcsdkPINVOKE.new_MeasurementField__SWIG_0(), true) {
  }

  /// <summary>Constructor.</summary>
  /// <param name="config">               to create a measurement field from.</param> 
  /// <param name="fieldId">              uniquely identifying the measurement field.</param> 
  /// <param name="referenceFrameWidth">  in pixels for scaling.</param> 
  /// <param name="referenceFrameHeight"> in pixels for scaling.</param> 
  /// <exception cref="SDKException"> if one the reference frame dimensions is zero.</exception>
  public MeasurementField(MeasurementFieldConfig config, long fieldId, int referenceFrameWidth, int referenceFrameHeight) : this(otcsdkPINVOKE.new_MeasurementField__SWIG_1(MeasurementFieldConfig.getCPtr(config), fieldId, referenceFrameWidth, referenceFrameHeight), true) {
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  ///  Copy constructor.
  public MeasurementField(MeasurementField rhs) : this(otcsdkPINVOKE.new_MeasurementField__SWIG_2(MeasurementField.getCPtr(rhs)), true) {
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Returns the configuration of the measurement field.</summary>
  /// <returns>configuration of the measurement field.</returns>
  public MeasurementFieldConfig getConfig() {
    MeasurementFieldConfig ret = new MeasurementFieldConfig(otcsdkPINVOKE.MeasurementField_getConfig(swigCPtr), true);
    return ret;
  }

  /// <summary>Returns the ID uniquely identifying the measurement field.</summary>
  /// <returns>ID of the measurement field.</returns>
  public long getId() {
    long ret = otcsdkPINVOKE.MeasurementField_getId(swigCPtr);
    return ret;
  }

  /// <summary>Returns the index of the measurement field.</summary>
  /// <returns>index of the measurement field.</returns>
  public int getIndex() {
    int ret = otcsdkPINVOKE.MeasurementField_getIndex(swigCPtr);
    return ret;
  }

  /// <summary>Sets the index of the measurement field.</summary>
  /// <param name="index"> to set.</param>
  public void setIndex(int index) {
    otcsdkPINVOKE.MeasurementField_setIndex(swigCPtr, index);
  }

  /// <summary>Returns the name of the measurement field.</summary>
  /// <returns>name of the measurement field.</returns>
  public string getName() {
    string ret = otcsdkPINVOKE.MeasurementField_getName(swigCPtr);
    return ret;
  }

  /// <summary>Sets the name of the measurement field.</summary>
  /// <param name="name"> of the measurement field.</param>
  public void setName(string name) {
    otcsdkPINVOKE.MeasurementField_setName(swigCPtr, name);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Returns the field data value at the given index.</summary>
  /// <param name="index"> of the desired field data.</param> 
  /// <returns>field data value at the given index.</returns> 
  /// <exception cref="SDKException"> if the index is out of range.</exception>
  public ushort getValue(int index) {
    ushort ret = otcsdkPINVOKE.MeasurementField_getValue__SWIG_0(swigCPtr, index);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the temperature in in °C at the given index.</summary>
  /// <param name="index"> of the desired field temperature.</param> 
  /// <returns>temperature in in °C at the given index.</returns> 
  /// <exception cref="SDKException"> if index is out of range.</exception>
  public float getTemperature(int index) {
    float ret = otcsdkPINVOKE.MeasurementField_getTemperature__SWIG_0(swigCPtr, index);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the field data value at the given coordinates.</summary>
  /// <param name="x"> coordinate.</param> 
  /// <param name="y"> coordinate.</param> 
  /// <returns>field data value at the given coordinates.</returns> 
  /// <exception cref="SDKException"> if the coordinates are out of range.</exception>
  public ushort getValue(int x, int y) {
    ushort ret = otcsdkPINVOKE.MeasurementField_getValue__SWIG_1(swigCPtr, x, y);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the temperature in in °C at the given coordinates.</summary>
  /// <param name="x"> coordinate.</param> 
  /// <param name="y"> coordinate.</param> 
  /// <returns>temperature in in °C at the given coordinate.</returns> 
  /// <exception cref="SDKException"> if the coordinates are out of range.</exception>
  public float getTemperature(int x, int y) {
    float ret = otcsdkPINVOKE.MeasurementField_getTemperature__SWIG_1(swigCPtr, x, y);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns an iterator with read access.</summary>
  /// The iterator traverses the measurement field in a row major fashion.
  /// <returns>iterator with read access.</returns>
  public ConstMeasurementFieldIterator getConstIterator() {
    ConstMeasurementFieldIterator ret = new ConstMeasurementFieldIterator(otcsdkPINVOKE.MeasurementField_getConstIterator(swigCPtr), true);
    return ret;
  }

  /// <summary>Returns the precision of the temperatures stored in the measurement field.</summary>
  /// <returns>precision of the temperatures stored in the measurement field.</returns>
  public TemperaturePrecision getTemperaturePrecision() {
    TemperaturePrecision ret = (TemperaturePrecision)otcsdkPINVOKE.MeasurementField_getTemperaturePrecision(swigCPtr);
    return ret;
  }

  /// <summary>Returns the x-coordinate of the upper left corner.</summary>
  /// <returns>x-coordinate of the upper left corner.</returns>
  public int getX() {
    int ret = otcsdkPINVOKE.MeasurementField_getX(swigCPtr);
    return ret;
  }

  /// <summary>Returns the y-coordinate of the upper left corner.</summary>
  /// <returns>y-coordinate of the upper left corner.</returns>
  public int getY() {
    int ret = otcsdkPINVOKE.MeasurementField_getY(swigCPtr);
    return ret;
  }

  /// <summary>Sets the position of the measurement field  by providing the coordinates of the upper       left corner.</summary>
  /// <param name="x"> coordinate of the upper left corner of the rectangular field.</param> 
  /// <param name="y"> coordinate of the upper left corner of the rectangular field.</param>
  public void setPosition(int x, int y) {
    otcsdkPINVOKE.MeasurementField_setPosition(swigCPtr, x, y);
  }

  /// <summary>Returns the shape of the measurement field.</summary>
  /// <returns>shape of the measurement field.</returns>
  public FieldShape getShape() {
    FieldShape ret = (FieldShape)otcsdkPINVOKE.MeasurementField_getShape(swigCPtr);
    return ret;
  }

  /// <summary>Returns the mode for the measurement field.</summary>
  /// <returns>mode for the measurement field.</returns>
  public FieldMode getMode() {
    FieldMode ret = (FieldMode)otcsdkPINVOKE.MeasurementField_getMode(swigCPtr);
    return ret;
  }

  /// <summary>Sets the mode for the measurement field.</summary>
  /// <param name="mode"> to set.</param>
  public void setMode(FieldMode mode) {
    otcsdkPINVOKE.MeasurementField_setMode(swigCPtr, (int)mode);
  }

  /// <summary>Returns the width in pixels of the field.</summary>
  /// <returns>width in pixels of the field.</returns>
  public int getWidth() {
    int ret = otcsdkPINVOKE.MeasurementField_getWidth(swigCPtr);
    return ret;
  }

  /// <summary>Returns the height in pixels of the field.</summary>
  /// <returns>height in pixels of the field.</returns>
  public int getHeight() {
    int ret = otcsdkPINVOKE.MeasurementField_getHeight(swigCPtr);
    return ret;
  }

  /// <summary>Returns the overall size of the field (width * height).</summary>
  /// <returns>size of the field.</returns>
  public int getSize() {
    int ret = otcsdkPINVOKE.MeasurementField_getSize(swigCPtr);
    return ret;
  }

  /// <summary>Resizes the measurement field.</summary>
  /// <param name="width">  in pixels of the resized measurement field.</param> 
  /// <param name="height"> in pixels of the resized measurement field.</param> 
  /// <exception cref="SDKException"> if one of the provided dimensions is equal or less than zero.</exception>
  public void resize(int width, int height) {
    otcsdkPINVOKE.MeasurementField_resize(swigCPtr, width, height);
  }

  /// <summary>Scales the position and dimensions of the measurement field based on new       frame dimensions.</summary>
  /// <param name="frameWidth">  new frame width in pixels.</param> 
  /// <param name="frameHeight"> new frame height in pixels.</param>
  public void scale(int frameWidth, int frameHeight) {
    otcsdkPINVOKE.MeasurementField_scale(swigCPtr, frameWidth, frameHeight);
  }

  /// <summary>Returns the source of the emissivity value.</summary>
  /// <returns>source of the emissivity value.</returns>
  public RadiationParameterSource getEmissivitySource() {
    RadiationParameterSource ret = (RadiationParameterSource)otcsdkPINVOKE.MeasurementField_getEmissivitySource(swigCPtr);
    return ret;
  }

  /// <summary>Returns the source of the transmissivity value.</summary>
  /// <returns>source of the transmissivity value.</returns>
  public RadiationParameterSource getTransmissivitySource() {
    RadiationParameterSource ret = (RadiationParameterSource)otcsdkPINVOKE.MeasurementField_getTransmissivitySource(swigCPtr);
    return ret;
  }

  /// <summary>Returns the source of the ambient temperature value.</summary>
  /// <returns>source of the ambient temperature value.</returns>
  public RadiationParameterSource getAmbientTemperatureSource() {
    RadiationParameterSource ret = (RadiationParameterSource)otcsdkPINVOKE.MeasurementField_getAmbientTemperatureSource(swigCPtr);
    return ret;
  }

  /// <summary>Grants read access to the radiation parameters used to process the measurement field.</summary>
  /// <returns>read access to the radiation parameters used to process the measurement field.</returns>
  public RadiationParameters getRadiationParameters() {
    RadiationParameters ret = new RadiationParameters(otcsdkPINVOKE.MeasurementField_getRadiationParameters(swigCPtr), true);
    return ret;
  }

  /// <summary>Sets the radiation parameters stored in the measurement field.</summary>
  /// <param name="radiation"> parameters to set.</param>
  public void setRadiationParameters(RadiationParameters radiation) {
    otcsdkPINVOKE.MeasurementField_setRadiationParameters(swigCPtr, RadiationParameters.getCPtr(radiation));
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Sets the sources of the radiation parameters.</summary>
  /// <param name="emissivitySource">         to set.</param> 
  /// <param name="ambientTemperatureSource"> to set.</param>
  public void setRadiationParameterSources(RadiationParameterSource emissivitySource, RadiationParameterSource ambientTemperatureSource) {
    otcsdkPINVOKE.MeasurementField_setRadiationParameterSources(swigCPtr, (int)emissivitySource, (int)ambientTemperatureSource);
  }

  /// <summary>Returns the overall mean temperature of the field in °C.</summary>
  /// <returns>overall mean temperature of the field in °C.</returns>
  public float getMeanTemperature() {
    float ret = otcsdkPINVOKE.MeasurementField_getMeanTemperature(swigCPtr);
    return ret;
  }

  /// <summary>Returns the minimum temperature in the field in °C.</summary>
  /// <returns>minimum temperature in the field in °C.</returns>
  public float getMinTemperature() {
    float ret = otcsdkPINVOKE.MeasurementField_getMinTemperature(swigCPtr);
    return ret;
  }

  /// <summary>Returns the maximum temperature in the field in °C.</summary>
  /// <returns>maximum temperature in the field in °C.</returns>
  public float getMaxTemperature() {
    float ret = otcsdkPINVOKE.MeasurementField_getMaxTemperature(swigCPtr);
    return ret;
  }

  /// <summary>Returns the data point specified by the the mode of this field.</summary>
  /// <returns>data point  specified by the the mode of this field.</returns>
  public float getDataPoint() {
    float ret = otcsdkPINVOKE.MeasurementField_getDataPoint(swigCPtr);
    return ret;
  }

  /// <summary>Sets the mean, minimum and maximum temperatures in °C.</summary>
  /// <param name="mean"> temperature in °C.</param> 
  /// <param name="min">  temperature in °C.</param> 
  /// <param name="max">  temperature in °C.</param>
  public void setTemperatures(float mean, float min, float max) {
    otcsdkPINVOKE.MeasurementField_setTemperatures(swigCPtr, mean, min, max);
  }

  /// <summary>Returns the temperature converter.</summary>
  /// It can be used to convert and validate the thermal frame values to and from temperatures in °C.
  /// <returns>temperature converter.</returns>
  public TemperatureConverter getConverter() {
    TemperatureConverter ret = new TemperatureConverter(otcsdkPINVOKE.MeasurementField_getConverter(swigCPtr), true);
    return ret;
  }

  /// <summary>Returns a complete copy of this frame.</summary>
  /// <returns>a complete copy of this frame.</returns>
  public MeasurementField clone() {
    MeasurementField ret = new MeasurementField(otcsdkPINVOKE.MeasurementField_clone(swigCPtr), true);
    return ret;
  }

  /// <summary>Copies the thermal data as degree Celsius to a one-dimensional array or vector.</summary>
  /// <remarks>Make sure the destination has at least the size returned by getSize().</remarks><param name="destination"> to copy the internal data to.</param> 
  /// <param name="size">        as element count. The specified size is limited to [0, getSize()].</param>
  public void copyTemperaturesTo(float[] destination, int size) {
    otcsdkPINVOKE.MeasurementField_copyTemperaturesTo(swigCPtr, destination, size);
  }

  /// <summary>Copies the internal values to a one-dimensional array or vector.</summary>
  /// <remarks>Make sure the destination has at least the size returned by getSize().</remarks><param name="destination"> to copy the internal data to.</param> 
  /// <param name="size">        as element count. The specified size is limited to [0, getSize()].</param>
  public void copyDataTo(ushort[] destination, int size) {
    otcsdkPINVOKE.MeasurementField_copyDataTo(swigCPtr, destination, size);
  }

}

}
