//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {
/// <summary>Defines the interface for classes realizing operation modes.</summary>
/// Each operation mode encapsulates a valid combination of the following configuration settings:
///  - Optics
///  - Temperature range
///  - Output video format
/// The available operation modes depend on the device, its optics, its calibrations, the video format
/// definitions and the type of connection to the device (USB, Ethernet).

public class OperationMode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal OperationMode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OperationMode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OperationMode() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          otcsdkPINVOKE.delete_OperationMode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <summary>Returns the index of the mode.</summary>
  /// Convenience method to easily locate the mode within the container returned by IRImager::getOperationModes().
  /// <returns>index of the mode.</returns> 
  /// <seealso cref="IRImager.getOperationModes"/>
  public virtual int getIndex() {
    int ret = otcsdkPINVOKE.OperationMode_getIndex(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the field of view in degrees of the optics.</summary>
  /// <returns>field of view in degrees of the optics.</returns>
  public virtual int getFieldOfView() {
    int ret = otcsdkPINVOKE.OperationMode_getFieldOfView(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns an optional string that further specifies the optics.</summary>
  /// <returns>optional string that further specifies the optics.</returns>
  public virtual string getOpticsText() {
    string ret = otcsdkPINVOKE.OperationMode_getOpticsText(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the serial number of the optics.</summary>
  /// <returns>serial number of the optics.</returns>
  public virtual int getOpticsSerialNumber() {
    int ret = otcsdkPINVOKE.OperationMode_getOpticsSerialNumber(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the lower limit temperature in °C.</summary>
  /// The returned temperature may vary depended on whether the temperature range is extended.
  /// <returns>lower limit temperature in °C.</returns> 
  /// <seealso cref="OperationMode.isTemperatureRangeExtended"/>
  public virtual float getTemperatureLowerLimit() {
    float ret = otcsdkPINVOKE.OperationMode_getTemperatureLowerLimit(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the upper limit temperature in °C.</summary>
  /// The returned temperature may vary depended on whether the temperature range is extended.
  /// <returns>upper limit temperature in °C.</returns> 
  /// <seealso cref="OperationMode.isTemperatureRangeExtended"/>
  public virtual float getTemperatureUpperLimit() {
    float ret = otcsdkPINVOKE.OperationMode_getTemperatureUpperLimit(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the lower non-extended limit temperature in °C.</summary>
  /// <returns>lower non-extended limit temperature in °C.</returns>
  public virtual float getTemperatureNormalLowerLimit() {
    float ret = otcsdkPINVOKE.OperationMode_getTemperatureNormalLowerLimit(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the upper non-extended limit temperature in °C.</summary>
  /// <returns>upper non-extended limit temperature in °C.</returns>
  public virtual float getTemperatureNormalUpperLimit() {
    float ret = otcsdkPINVOKE.OperationMode_getTemperatureNormalUpperLimit(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the lower extended limit temperature in °C.</summary>
  /// The extended limit will equal the non-extended one, if the temperature range is not extendable.
  /// <returns>lower extended limit temperature in °C.</returns>
  public virtual float getTemperatureExtendedLowerLimit() {
    float ret = otcsdkPINVOKE.OperationMode_getTemperatureExtendedLowerLimit(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the upper extended limit temperature in °C.</summary>
  /// The extended limit will equal the non-extended one, if the temperature range is not extendable.
  /// <returns>upper extended limit temperature in °C.</returns>
  public virtual float getTemperatureExtendedUpperLimit() {
    float ret = otcsdkPINVOKE.OperationMode_getTemperatureExtendedUpperLimit(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns whether the temperature range is currently extended.</summary>
  /// The return value depends on whether the temperature range can actually be extended and whether temperature
  /// range extension is enabled.
  /// <returns>true, if the temperature range is currently extended. False, otherwise.</returns> 
  /// <seealso cref="OperationMode.isTemperatureRangeExtendable"/>
  public virtual bool isTemperatureRangeExtended() {
    bool ret = otcsdkPINVOKE.OperationMode_isTemperatureRangeExtended(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns whether the temperature range can be extended.</summary>
  /// Not all temperature ranges can be extended.
  /// <returns>true, if the temperature range can be extended. False, otherwise.</returns>
  public virtual bool isTemperatureRangeExtendable() {
    bool ret = otcsdkPINVOKE.OperationMode_isTemperatureRangeExtendable(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns whether the temperatures were measured with high precision.</summary>
  /// The return value depends on whether the temperature range actually feature high precision measurements
  /// and whether high precision is enabled.
  /// <returns>true if the temperatures were measured with high precision. False if the standard precision was
  ///             used.</returns> 
  /// <seealso cref="OperationMode.isTemperatureHighPrecisionAvailable"/>
  public virtual bool isTemperatureHighPrecision() {
    bool ret = otcsdkPINVOKE.OperationMode_isTemperatureHighPrecision(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns whether measurements with high precision are available for the temperature range.</summary>
  /// Not all temperature ranges on all devices feature high precision temperature measurements.
  /// <returns>true, if measurements with high precision are available for the temperature range. False,
  ///             otherwise.</returns>
  public virtual bool isTemperatureHighPrecisionAvailable() {
    bool ret = otcsdkPINVOKE.OperationMode_isTemperatureHighPrecisionAvailable(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the width of the frame in pixels.</summary>
  /// <returns>width of the frame in pixels.</returns>
  public virtual int getFrameWidth() {
    int ret = otcsdkPINVOKE.OperationMode_getFrameWidth(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the height of the frame in pixels.</summary>
  /// <returns>height of the frame in pixels.</returns>
  public virtual int getFrameHeight() {
    int ret = otcsdkPINVOKE.OperationMode_getFrameHeight(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns the framerate in Hz (not sub-sampled).</summary>
  /// <returns>framerate in Hz (not sub-sampled).</returns>
  public virtual int getFramerate() {
    int ret = otcsdkPINVOKE.OperationMode_getFramerate(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>Returns a string representation of the operation mode.</summary>
  /// <returns>string representation of the operation mode.</returns>
  public virtual string toString() {
    string ret = otcsdkPINVOKE.OperationMode_toString(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
