//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the available modes for PIF analog input channels.
public enum PifAiMode {
  ///  Off.
  Off,
  ///  The shutter flag is controlled by the input voltage.
  FlagControl,
  ///  Emissivity for the thermal frame is derived from the input voltage.
  Emissivity,
  ///  Ambient temperature for the thermal frame is derived from the input voltage.
  AmbientTemperature,
  ///  The input voltage value is transformed and provided to IRImagerClients via a callback.
  UncommittedValue
}

}
