//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the supported PIF device types.
public enum PifDeviceType {
  ///  Use the PIF type reported by the camera firmware.
  Automatic,
  ///  No PIF.
  None,
  ///  Standard PIF.
  Standard,
  ///  Industrial PIF with voltage based analog outputs.
  IndustrialMV,
  ///  Industrial PIF with current based analog outputs.
  IndustrialMA,
  ///  Internal PIF.
  Internal,
  ///  Stackable PIF.
  Stackable,
  ///  Instead of a PIF an external temperature probe is used.
  TemperatureProbe,
  ///  The pins of the PIF connector on the camera are used directly.
  Proprietary
}

}
