//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {
/// <summary>Encapsulates the configuration for a PIF digital output channel.</summary>
/// For a detailed overview of all available modes and parameters please refer to the corresponding section in the documentation
/// of the [configuration file](#important-files-configuration-process-interface-digital-outputs).

public class PifDoConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PifDoConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PifDoConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PifDoConfig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PifDoConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otcsdkPINVOKE.delete_PifDoConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  ///  Constructor.
  public PifDoConfig() : this(otcsdkPINVOKE.new_PifDoConfig(), true) {
  }

  /// <summary>Creates a configuration for the mode PifDoMode::Off.</summary>
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <returns>configuration for the mode PifDoMode::Off.</returns>
  public static PifDoConfig createOff(int deviceIndex, int pinIndex) {
    PifDoConfig ret = new PifDoConfig(otcsdkPINVOKE.PifDoConfig_createOff(deviceIndex, pinIndex), true);
    return ret;
  }

  /// <summary>Creates a configuration for the mode PifDoMode::FlagStatus.</summary>
  /// <remarks>This mode is __unique__ and can only be applied once for __all__ channels.</remarks>
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <param name="lowIfOpen">   if true, a low signal will be output, if the flag is open.</param> 
  /// <returns>configuration for the mode PifDoMode::FlagStatus.</returns>
  public static PifDoConfig createFlagStatus(int deviceIndex, int pinIndex, bool lowIfOpen) {
    PifDoConfig ret = new PifDoConfig(otcsdkPINVOKE.PifDoConfig_createFlagStatus(deviceIndex, pinIndex, lowIfOpen), true);
    return ret;
  }

  /// <summary>Create a configuration for the mode PifDoMode::FrameSync.</summary>
  /// <remarks>This mode is __unique__ and can only be applied once for __all__ channels.</remarks>
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <returns>configuration for the mode PifDoMode::FrameSync.</returns>
  public static PifDoConfig createFrameSync(int deviceIndex, int pinIndex) {
    PifDoConfig ret = new PifDoConfig(otcsdkPINVOKE.PifDoConfig_createFrameSync(deviceIndex, pinIndex), true);
    return ret;
  }

  /// <summary>Creates a configuration for the mode PifDoMode::ExternalCommunication.</summary>
  /// When set to external communication the output value of the channel can be set with ProcessInterface::setDoValue().
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <returns>configuration for the mode PifDoMode::ExternalCommunication.</returns>
  public static PifDoConfig createExternalCommunication(int deviceIndex, int pinIndex) {
    PifDoConfig ret = new PifDoConfig(otcsdkPINVOKE.PifDoConfig_createExternalCommunication(deviceIndex, pinIndex), true);
    return ret;
  }

  /// <summary>Creates a configuration for the mode PifDoMode::FailSafe.</summary>
  /// Refer to the [Fail Safe](#fail-safe) chapter for more details.
  /// <remarks>This mode is __unique__ and can only be applied once for __all__ channels.</remarks>
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <returns>configuration for the mode PifDoMode::FailSafe.</returns>
  public static PifDoConfig createFailSafe(int deviceIndex, int pinIndex) {
    PifDoConfig ret = new PifDoConfig(otcsdkPINVOKE.PifDoConfig_createFailSafe(deviceIndex, pinIndex), true);
    return ret;
  }

  ///  Identifies the channel by specifying the PIF device on which its pins are located.
  public int deviceIndex {
    set {
      otcsdkPINVOKE.PifDoConfig_deviceIndex_set(swigCPtr, value);
    } 
    get {
      int ret = otcsdkPINVOKE.PifDoConfig_deviceIndex_get(swigCPtr);
      return ret;
    } 
  }

  ///  Identifies the channel by locating its pins on the specified PIF device.
  public int pinIndex {
    set {
      otcsdkPINVOKE.PifDoConfig_pinIndex_set(swigCPtr, value);
    } 
    get {
      int ret = otcsdkPINVOKE.PifDoConfig_pinIndex_get(swigCPtr);
      return ret;
    } 
  }

  ///  Mode to be applied to the channel.
  public PifDoMode mode {
    set {
      otcsdkPINVOKE.PifDoConfig_mode_set(swigCPtr, (int)value);
    } 
    get {
      PifDoMode ret = (PifDoMode)otcsdkPINVOKE.PifDoConfig_mode_get(swigCPtr);
      return ret;
    } 
  }

  ///  Indicates if the output is low active.
  public bool outputLowActive {
    set {
      otcsdkPINVOKE.PifDoConfig_outputLowActive_set(swigCPtr, value);
    } 
    get {
      bool ret = otcsdkPINVOKE.PifDoConfig_outputLowActive_get(swigCPtr);
      return ret;
    } 
  }

}

}
