//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {
/// <summary>Encapsulates the parameters of a linear transformation.</summary>
/// y(x) = gain * x + offset

public class Slope : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Slope(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Slope obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Slope obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Slope() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otcsdkPINVOKE.delete_Slope(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  ///  Constructor.
  public Slope() : this(otcsdkPINVOKE.new_Slope__SWIG_0(), true) {
  }

  /// <summary>Constructor.</summary>
  /// <param name="gain">   of the linear transformation.</param> 
  /// <param name="offset"> of the linear transformation.</param>
  public Slope(float gain, float offset) : this(otcsdkPINVOKE.new_Slope__SWIG_1(gain, offset), true) {
  }

  ///  Gain of the linear transformation.
  public float gain {
    set {
      otcsdkPINVOKE.Slope_gain_set(swigCPtr, value);
    } 
    get {
      float ret = otcsdkPINVOKE.Slope_gain_get(swigCPtr);
      return ret;
    } 
  }

  ///  Offset of the linear transformation.
  public float offset {
    set {
      otcsdkPINVOKE.Slope_offset_set(swigCPtr, value);
    } 
    get {
      float ret = otcsdkPINVOKE.Slope_offset_get(swigCPtr);
      return ret;
    } 
  }

}

}
