//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the different field modes that define what data point is calculated.
public enum FieldMode {
  ///  Minimum temperature in °C.
  Minimum,
  ///  Maximum temperature in °C.
  Maximum,
  ///  Mean temperature in °C.
  Mean
}

}
