//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {
/// <summary>Encapsulates the configuration for a PIF analog output channel.</summary>
/// For a detailed overview of all available modes and parameters please refer to the corresponding section in the documentation
/// of the [configuration file](#important-files-configuration-process-interface-analog-outputs).

public class PifAoConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PifAoConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PifAoConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PifAoConfig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PifAoConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otcsdkPINVOKE.delete_PifAoConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  ///  Constructor.
  public PifAoConfig() : this(otcsdkPINVOKE.new_PifAoConfig(), true) {
  }

  /// <summary>Creates a configuration for the mode PifAoMode::Off.</summary>
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <returns>configuration for the mode PifAoMode::Off.</returns>
  public static PifAoConfig createOff(int deviceIndex, int pinIndex) {
    PifAoConfig ret = new PifAoConfig(otcsdkPINVOKE.PifAoConfig_createOff(deviceIndex, pinIndex), true);
    return ret;
  }

  /// <summary>Creates a configuration for the mode PifAoMode::ExternalCommunication.</summary>
  /// When set to external communication the output value of the channel can be set with ProcessInterface::setAoValue().
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <param name="outputMode">  to apply.</param> 
  /// <returns>configuration for the mode PifAoMode::ExternalCommunication.</returns>
  public static PifAoConfig createExternalCommunication(int deviceIndex, int pinIndex, PifAoOutputMode outputMode) {
    PifAoConfig ret = new PifAoConfig(otcsdkPINVOKE.PifAoConfig_createExternalCommunication(deviceIndex, pinIndex, (int)outputMode), true);
    return ret;
  }

  /// <summary>Creates a configuration for the mode PifAoMode::FlagStatus.</summary>
  /// The values for open, moving and closed are automatically clipped to the specified output mode limits.
  /// <remarks>This mode is __unique__ and can only be applied once for __all__ channels.</remarks>
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <param name="outputMode">  to apply.</param> 
  /// <param name="open">        value to output if the shutter flag is open.</param> 
  /// <param name="moving">      value to output if the shutter flag is moving.</param> 
  /// <param name="closed">      value to output if the shutter flag is closed.</param> 
  /// <returns>configuration for the mode PifAoMode::FlagStatus.</returns>
  public static PifAoConfig createFlagStatus(int deviceIndex, int pinIndex, PifAoOutputMode outputMode, float open, float moving, float closed) {
    PifAoConfig ret = new PifAoConfig(otcsdkPINVOKE.PifAoConfig_createFlagStatus(deviceIndex, pinIndex, (int)outputMode, open, moving, closed), true);
    return ret;
  }

  /// <summary>Creates a configuration for the mode PifAoMode::FrameSync.</summary>
  /// The value for pulse will automatically be clipped to the specified output mode limits.
  /// <remarks>This mode is __unique__ and can only be applied once for __all__ channels.</remarks>
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <param name="outputMode">  to apply.</param> 
  /// <param name="pulse">       height of the generated pulse indicating an newly captured frame.</param> 
  /// <returns>configuration for the mode PifAoMode::FrameSync.</returns>
  public static PifAoConfig createFrameSync(int deviceIndex, int pinIndex, PifAoOutputMode outputMode, float pulse) {
    PifAoConfig ret = new PifAoConfig(otcsdkPINVOKE.PifAoConfig_createFrameSync(deviceIndex, pinIndex, (int)outputMode, pulse), true);
    return ret;
  }

  /// <summary>Creates a configuration for the mode PifAoMode::InternalTemperature.</summary>
  /// The internal temperature t_internal is converted into an output value X_out as follows:
  /// `X_out = gain * t_internal + offset`
  /// <remarks>This mode is __unique__ and can only be applied once for __all__ channels.</remarks>
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <param name="outputMode">  to apply.</param> 
  /// <param name="gain">        for converting the internal temperature into an output value.</param> 
  /// <param name="offset">      for converting the internal temperature into an output value.</param> 
  /// <returns>configuration for the mode PifAoMode::InternalTemperature.</returns>
  public static PifAoConfig createInternalTemperature(int deviceIndex, int pinIndex, PifAoOutputMode outputMode, float gain, float offset) {
    PifAoConfig ret = new PifAoConfig(otcsdkPINVOKE.PifAoConfig_createInternalTemperature(deviceIndex, pinIndex, (int)outputMode, gain, offset), true);
    return ret;
  }

  /// <summary>Creates a configuration for the mode PifAoMode::MeasurementField.</summary>
  /// The data point of the measurement field that will be output is given by the value of the MeasurementFieldConfig::mode
  /// and can be accessed through MeasurementField::getDataPoint(). Its value x_field is converted into an output value X_out
  /// as follows:
  /// `X_out = gain * x_field + offset`
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <param name="outputMode">  to apply.</param> 
  /// <param name="fieldIndex">  identifying the measurement field. It start at 0 and increments with every measurement field that is added.
  ///                            The method IRImager::addMeasurementField() will return the index of the added field.</param> 
  /// <param name="gain">        for converting the measurement field data point into an output value.</param> 
  /// <param name="offset">      for converting the measurement field data point into an output value.</param> 
  /// <returns>configuration for the mode PifAoMode::MeasurementField.</returns>
  public static PifAoConfig createMeasurementField(int deviceIndex, int pinIndex, PifAoOutputMode outputMode, int fieldIndex, float gain, float offset) {
    PifAoConfig ret = new PifAoConfig(otcsdkPINVOKE.PifAoConfig_createMeasurementField(deviceIndex, pinIndex, (int)outputMode, fieldIndex, gain, offset), true);
    return ret;
  }

  /// <summary>Creates a configuration for the mode PifAoMode::FailSafe.</summary>
  /// Refer to the [Fail Safe](#fail-safe) chapter for more details.
  /// The value for pulse will automatically be clipped to the specified output mode limits.
  /// <remarks>This mode is __unique__ and can only be applied once for __all__ channels.</remarks>
  /// <param name="deviceIndex"> identifying the channel.</param> 
  /// <param name="pinIndex">    identifying the channel.</param> 
  /// <param name="outputMode">  to apply.</param> 
  /// <param name="pulse">       height of the output heart beat signal.</param> 
  /// <returns>configuration for the mode PifAoMode::FailSafe.</returns>
  public static PifAoConfig createFailSafe(int deviceIndex, int pinIndex, PifAoOutputMode outputMode, float pulse) {
    PifAoConfig ret = new PifAoConfig(otcsdkPINVOKE.PifAoConfig_createFailSafe(deviceIndex, pinIndex, (int)outputMode, pulse), true);
    return ret;
  }

  ///  Identifies the channel by specifying the PIF device on which its pins are located.
  public int deviceIndex {
    set {
      otcsdkPINVOKE.PifAoConfig_deviceIndex_set(swigCPtr, value);
    } 
    get {
      int ret = otcsdkPINVOKE.PifAoConfig_deviceIndex_get(swigCPtr);
      return ret;
    } 
  }

  ///  Identifies the channel by locating its pins on the specified PIF device.
  public int pinIndex {
    set {
      otcsdkPINVOKE.PifAoConfig_pinIndex_set(swigCPtr, value);
    } 
    get {
      int ret = otcsdkPINVOKE.PifAoConfig_pinIndex_get(swigCPtr);
      return ret;
    } 
  }

  ///  Mode to be applied to the channel.
  public PifAoMode mode {
    set {
      otcsdkPINVOKE.PifAoConfig_mode_set(swigCPtr, (int)value);
    } 
    get {
      PifAoMode ret = (PifAoMode)otcsdkPINVOKE.PifAoConfig_mode_get(swigCPtr);
      return ret;
    } 
  }

  ///  Output mode to be applied to the channel.
  public PifAoOutputMode outputMode {
    set {
      otcsdkPINVOKE.PifAoConfig_outputMode_set(swigCPtr, (int)value);
    } 
    get {
      PifAoOutputMode ret = (PifAoOutputMode)otcsdkPINVOKE.PifAoConfig_outputMode_get(swigCPtr);
      return ret;
    } 
  }

  ///  Defines how data points are converted into output values.
  public Slope slope {
    set {
      otcsdkPINVOKE.PifAoConfig_slope_set(swigCPtr, Slope.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = otcsdkPINVOKE.PifAoConfig_slope_get(swigCPtr);
      Slope ret = (cPtr == global::System.IntPtr.Zero) ? null : new Slope(cPtr, false);
      return ret;
    } 
  }

  ///  Identifies the measurement field by its index.
  public int fieldIndex {
    set {
      otcsdkPINVOKE.PifAoConfig_fieldIndex_set(swigCPtr, value);
    } 
    get {
      int ret = otcsdkPINVOKE.PifAoConfig_fieldIndex_get(swigCPtr);
      return ret;
    } 
  }

  ///  Output value for an active event/state.
  public float outputActive {
    set {
      otcsdkPINVOKE.PifAoConfig_outputActive_set(swigCPtr, value);
    } 
    get {
      float ret = otcsdkPINVOKE.PifAoConfig_outputActive_get(swigCPtr);
      return ret;
    } 
  }

  ///  Output value for an intermediate event/state.
  public float outputIntermediate {
    set {
      otcsdkPINVOKE.PifAoConfig_outputIntermediate_set(swigCPtr, value);
    } 
    get {
      float ret = otcsdkPINVOKE.PifAoConfig_outputIntermediate_get(swigCPtr);
      return ret;
    } 
  }

  ///  Output value for an inactive event/state.
  public float outputInactive {
    set {
      otcsdkPINVOKE.PifAoConfig_outputInactive_set(swigCPtr, value);
    } 
    get {
      float ret = otcsdkPINVOKE.PifAoConfig_outputInactive_get(swigCPtr);
      return ret;
    } 
  }

}

}
