//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

public class PifAnalogInputConfigVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<PifAiConfig>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PifAnalogInputConfigVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PifAnalogInputConfigVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PifAnalogInputConfigVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PifAnalogInputConfigVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otcsdkPINVOKE.delete_PifAnalogInputConfigVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PifAnalogInputConfigVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (PifAiConfig element in c) {
      this.Add(element);
    }
  }

  public PifAnalogInputConfigVector(global::System.Collections.Generic.IEnumerable<PifAiConfig> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (PifAiConfig element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public PifAiConfig this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(PifAiConfig[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(PifAiConfig[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, PifAiConfig[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public PifAiConfig[] ToArray() {
    PifAiConfig[] array = new PifAiConfig[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<PifAiConfig> global::System.Collections.Generic.IEnumerable<PifAiConfig>.GetEnumerator() {
    return new PifAnalogInputConfigVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new PifAnalogInputConfigVectorEnumerator(this);
  }

  public PifAnalogInputConfigVectorEnumerator GetEnumerator() {
    return new PifAnalogInputConfigVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class PifAnalogInputConfigVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<PifAiConfig>
  {
    private PifAnalogInputConfigVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public PifAnalogInputConfigVectorEnumerator(PifAnalogInputConfigVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public PifAiConfig Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (PifAiConfig)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public PifAnalogInputConfigVector() : this(otcsdkPINVOKE.new_PifAnalogInputConfigVector__SWIG_0(), true) {
  }

  public PifAnalogInputConfigVector(PifAnalogInputConfigVector other) : this(otcsdkPINVOKE.new_PifAnalogInputConfigVector__SWIG_1(PifAnalogInputConfigVector.getCPtr(other)), true) {
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    otcsdkPINVOKE.PifAnalogInputConfigVector_Clear(swigCPtr);
  }

  public void Add(PifAiConfig x) {
    otcsdkPINVOKE.PifAnalogInputConfigVector_Add(swigCPtr, PifAiConfig.getCPtr(x));
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = otcsdkPINVOKE.PifAnalogInputConfigVector_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = otcsdkPINVOKE.PifAnalogInputConfigVector_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = otcsdkPINVOKE.PifAnalogInputConfigVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    otcsdkPINVOKE.PifAnalogInputConfigVector_reserve(swigCPtr, n);
  }

  public PifAnalogInputConfigVector(int capacity) : this(otcsdkPINVOKE.new_PifAnalogInputConfigVector__SWIG_2(capacity), true) {
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  private PifAiConfig getitemcopy(int index) {
    PifAiConfig ret = new PifAiConfig(otcsdkPINVOKE.PifAnalogInputConfigVector_getitemcopy(swigCPtr, index), true);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private PifAiConfig getitem(int index) {
    PifAiConfig ret = new PifAiConfig(otcsdkPINVOKE.PifAnalogInputConfigVector_getitem(swigCPtr, index), false);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, PifAiConfig val) {
    otcsdkPINVOKE.PifAnalogInputConfigVector_setitem(swigCPtr, index, PifAiConfig.getCPtr(val));
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(PifAnalogInputConfigVector values) {
    otcsdkPINVOKE.PifAnalogInputConfigVector_AddRange(swigCPtr, PifAnalogInputConfigVector.getCPtr(values));
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public PifAnalogInputConfigVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = otcsdkPINVOKE.PifAnalogInputConfigVector_GetRange(swigCPtr, index, count);
    PifAnalogInputConfigVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new PifAnalogInputConfigVector(cPtr, true);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, PifAiConfig x) {
    otcsdkPINVOKE.PifAnalogInputConfigVector_Insert(swigCPtr, index, PifAiConfig.getCPtr(x));
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, PifAnalogInputConfigVector values) {
    otcsdkPINVOKE.PifAnalogInputConfigVector_InsertRange(swigCPtr, index, PifAnalogInputConfigVector.getCPtr(values));
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    otcsdkPINVOKE.PifAnalogInputConfigVector_RemoveAt(swigCPtr, index);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    otcsdkPINVOKE.PifAnalogInputConfigVector_RemoveRange(swigCPtr, index, count);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public static PifAnalogInputConfigVector Repeat(PifAiConfig value, int count) {
    global::System.IntPtr cPtr = otcsdkPINVOKE.PifAnalogInputConfigVector_Repeat(PifAiConfig.getCPtr(value), count);
    PifAnalogInputConfigVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new PifAnalogInputConfigVector(cPtr, true);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    otcsdkPINVOKE.PifAnalogInputConfigVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    otcsdkPINVOKE.PifAnalogInputConfigVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, PifAnalogInputConfigVector values) {
    otcsdkPINVOKE.PifAnalogInputConfigVector_SetRange(swigCPtr, index, PifAnalogInputConfigVector.getCPtr(values));
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
