//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {
///  Encapsulates the configuration of a measurement field.

public class MeasurementFieldConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MeasurementFieldConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MeasurementFieldConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MeasurementFieldConfig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MeasurementFieldConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otcsdkPINVOKE.delete_MeasurementFieldConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  ///  Constructor.
  public MeasurementFieldConfig() : this(otcsdkPINVOKE.new_MeasurementFieldConfig(), true) {
  }

  /// <summary>Validates the configuration settings.</summary>
  /// <exception cref="SDKException"> if the configuration contains invalid settings.</exception>
  public void validate() {
    otcsdkPINVOKE.MeasurementFieldConfig_validate(swigCPtr);
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  ///  Name of the measurement field.
  public string name {
    set {
      otcsdkPINVOKE.MeasurementFieldConfig_name_set(swigCPtr, value);
      if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = otcsdkPINVOKE.MeasurementFieldConfig_name_get(swigCPtr);
      if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  ///  Shape of the measurement field.
  public FieldShape shape {
    set {
      otcsdkPINVOKE.MeasurementFieldConfig_shape_set(swigCPtr, (int)value);
    } 
    get {
      FieldShape ret = (FieldShape)otcsdkPINVOKE.MeasurementFieldConfig_shape_get(swigCPtr);
      return ret;
    } 
  }

  ///  Mode for the measurement field.
  public FieldMode mode {
    set {
      otcsdkPINVOKE.MeasurementFieldConfig_mode_set(swigCPtr, (int)value);
    } 
    get {
      FieldMode ret = (FieldMode)otcsdkPINVOKE.MeasurementFieldConfig_mode_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>x position of the measurement field in pixels.</summary>
  /// Depending of the shape of the field this may refer to different things:
  /// - rectangle: Position of the upper left corner.
  public int positionX {
    set {
      otcsdkPINVOKE.MeasurementFieldConfig_positionX_set(swigCPtr, value);
    } 
    get {
      int ret = otcsdkPINVOKE.MeasurementFieldConfig_positionX_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>y position of the measurement field in pixels.</summary>
  /// Depending of the shape of the field this may refer to different things:
  /// - rectangle: Position of the upper left corner.
  public int positionY {
    set {
      otcsdkPINVOKE.MeasurementFieldConfig_positionY_set(swigCPtr, value);
    } 
    get {
      int ret = otcsdkPINVOKE.MeasurementFieldConfig_positionY_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>Width of the measurement field in pixels.</summary>
  /// Applicable for the following shapes:
  /// - rectangle
  public int width {
    set {
      otcsdkPINVOKE.MeasurementFieldConfig_width_set(swigCPtr, value);
    } 
    get {
      int ret = otcsdkPINVOKE.MeasurementFieldConfig_width_get(swigCPtr);
      return ret;
    } 
  }

  /// <summary>Height of the measurement field in pixels.</summary>
  /// Applicable for the following shapes:
  /// - rectangle
  public int height {
    set {
      otcsdkPINVOKE.MeasurementFieldConfig_height_set(swigCPtr, value);
    } 
    get {
      int ret = otcsdkPINVOKE.MeasurementFieldConfig_height_get(swigCPtr);
      return ret;
    } 
  }

  ///  Radiation parameters for the measurement field.
  public RadiationParameters radiation {
    set {
      otcsdkPINVOKE.MeasurementFieldConfig_radiation_set(swigCPtr, RadiationParameters.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = otcsdkPINVOKE.MeasurementFieldConfig_radiation_get(swigCPtr);
      RadiationParameters ret = (cPtr == global::System.IntPtr.Zero) ? null : new RadiationParameters(cPtr, false);
      return ret;
    } 
  }

}

}
