//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

public class otcsdk {
  /// <summary>Returns whether the given device is PI.</summary>
  /// <param name="type"> imager device type to check.</param> 
  /// <returns>true if the given device is a PI. False otherwise.</returns>
  public static bool isPI(DeviceType type) {
    bool ret = otcsdkPINVOKE.isPI((int)type);
    return ret;
  }

  /// <summary>Returns whether the given device is a Xi.</summary>
  /// <param name="type"> imager device type to check.</param> 
  /// <returns>true if the given device is a Xi. False otherwise.</returns>
  public static bool isXI(DeviceType type) {
    bool ret = otcsdkPINVOKE.isXI((int)type);
    return ret;
  }

  /// <summary>Returns whether the given device is an MT device.</summary>
  /// <param name="type"> imager device type to check.</param> 
  /// <returns>true if the given device is of the MT variety. False otherwise.</returns>
  public static bool isMTDevice(DeviceType type) {
    bool ret = otcsdkPINVOKE.isMTDevice((int)type);
    return ret;
  }

  /// <summary>Returns whether the given device will answer on all commands, also on commands with no answer needed (such as set commands).</summary>
  /// <param name="type"> imager device type to check.</param> 
  /// <returns>true if the given device answers on all commands. False otherwise.</returns>
  public static bool isDeviceAnsweringAllCommands(DeviceType type) {
    bool ret = otcsdkPINVOKE.isDeviceAnsweringAllCommands((int)type);
    return ret;
  }

  /// <summary>Returns whether the given device supports the autonomous mode.</summary>
  /// <param name="type"> imager device type to check.</param> 
  /// <returns>true if the given device supports the autonomous mode. False otherwise.</returns>
  public static bool isAutonomousDevice(DeviceType type) {
    bool ret = otcsdkPINVOKE.isAutonomousDevice((int)type);
    return ret;
  }

  /// <summary>Returns whether the given device supports Ethernet.</summary>
  /// <param name="type"> imager device type to check.</param> 
  /// <returns>true if the given device supports Ethernet. False otherwise.</returns>
  public static bool isEthernetDevice(DeviceType type) {
    bool ret = otcsdkPINVOKE.isEthernetDevice((int)type);
    return ret;
  }

  /// <summary>Returns a string representation of the given device type.</summary>
  /// Use `deviceTypeToString()` in Python instead.
  /// <param name="deviceType"> for which a string representation is desired.</param> 
  /// <returns>string respresentation of the given device type.</returns>
  public static string toString(DeviceType deviceType) {
    string ret = otcsdkPINVOKE.toString__SWIG_0((int)deviceType);
    return ret;
  }

  /// <summary>Returns a string representation of the given flag state.</summary>
  /// Use `flagStateToString()` in Python instead.
  /// <param name="flagState"> for which a string representation is desired.</param> 
  /// <returns>string representation of the given flag state.</returns>
  public static string toString(FlagState flagState) {
    string ret = otcsdkPINVOKE.toString__SWIG_1((int)flagState);
    return ret;
  }

  public static float INVALID_TEMPERATURE {
    get {
      float ret = otcsdkPINVOKE.INVALID_TEMPERATURE_get();
      return ret;
    } 
  }

  public static ushort INVALID_VALUE {
    get {
      ushort ret = otcsdkPINVOKE.INVALID_VALUE_get();
      return ret;
    } 
  }

  /// <summary>Returns a string representation of the given temperature precision.</summary>
  /// Use `temperaturePrecisionToString()` in Python instead.
  /// <param name="precision"> for which a string representation is desired.</param> 
  /// <returns>string respresentation of the given temperature precision.</returns>
  public static string toString(TemperaturePrecision precision) {
    string ret = otcsdkPINVOKE.toString__SWIG_2((int)precision);
    return ret;
  }

  /// <summary>Returns a string representation of the given radiation parameter source.</summary>
  /// Use `radiationParameterSourceToString()` in Python instead.
  /// <param name="source"> for which a string representation is desired.</param> 
  /// <returns>string representation of the given radiation parameter source.</returns>
  public static string toString(RadiationParameterSource source) {
    string ret = otcsdkPINVOKE.toString__SWIG_3((int)source);
    return ret;
  }

  /// <summary>Returns a string representation of the given field shape.</summary>
  /// Use `fieldShapeToString()` in Python instead.
  /// <param name="shape"> for which a string representation is desired.</param> 
  /// <returns>string representation of the given field shape.</returns>
  public static string toString(FieldShape shape) {
    string ret = otcsdkPINVOKE.toString__SWIG_4((int)shape);
    return ret;
  }

  /// <summary>Returns a string representation of the given field mode.</summary>
  /// Use `fieldModeToString()` in Python instead.
  /// <param name="fieldMode"> for which a string representation is desired.</param> 
  /// <returns>string representation of the given field mode.</returns>
  public static string toString(FieldMode fieldMode) {
    string ret = otcsdkPINVOKE.toString__SWIG_5((int)fieldMode);
    return ret;
  }

  /// <summary>Returns the lower limit of the specified PIF analog output mode as a number value.</summary>
  /// <param name="outputMode"> for which the lower limit is desired.</param> 
  /// <returns>lower limit of the specified PIF analog output mode as a number value.</returns>
  public static float lowerLimit(PifAoOutputMode outputMode) {
    float ret = otcsdkPINVOKE.lowerLimit((int)outputMode);
    return ret;
  }

  /// <summary>Returns the upper limit of the specified PIF analog output mode as a number value.</summary>
  /// <param name="outputMode"> for which the upper limit is desired.</param> 
  /// <returns>upper limit of the specified PIF analog output mode as a number value.</returns>
  public static float upperLimit(PifAoOutputMode outputMode) {
    float ret = otcsdkPINVOKE.upperLimit((int)outputMode);
    return ret;
  }

  /// <summary>Clamps the given value to the limits of the specified PIF analog output mode.</summary>
  /// <param name="value">      to clamp.</param> 
  /// <param name="outputMode"> to which the provided value should be clamped.</param> 
  /// <returns>the given value to the limits of the specified PIF analog output mode.</returns>
  public static float clampValue(float value, PifAoOutputMode outputMode) {
    float ret = otcsdkPINVOKE.clampValue(value, (int)outputMode);
    return ret;
  }

  /// <summary>Returns a string representation of the given PIF device type.</summary>
  /// Use `pifDeviceTypeToString()` in Python instead.
  /// <param name="type"> for which a string representation is desired.</param> 
  /// <returns>string respresentation of the given PIF device type.</returns>
  public static string toString(PifDeviceType type) {
    string ret = otcsdkPINVOKE.toString__SWIG_6((int)type);
    return ret;
  }

  /// <summary>Returns a string representation of the given PIF analog input mode.</summary>
  /// Use `pifAiModeToString()` in Python instead.
  /// <param name="analogInputMode"> for which a string representation is desired.</param> 
  /// <returns>string respresentation of the given PIF analog input mode.</returns>
  public static string toString(PifAiMode analogInputMode) {
    string ret = otcsdkPINVOKE.toString__SWIG_7((int)analogInputMode);
    return ret;
  }

  /// <summary>Returns a string representation of the given PIF digital input mode.</summary>
  /// Use `pifDiModeToString()` in Python instead.
  /// <param name="digitalInputMode"> for which a string representation is desired.</param> 
  /// <returns>string respresentation of the given PIF digital input mode.</returns>
  public static string toString(PifDiMode digitalInputMode) {
    string ret = otcsdkPINVOKE.toString__SWIG_8((int)digitalInputMode);
    return ret;
  }

  /// <summary>Returns a string representation of the given PIF analog output mode.</summary>
  /// Use `pifAoModeToString()` in Python instead.
  /// <param name="analogOutputMode"> for which a string representation is desired.</param> 
  /// <returns>string respresentation of the given PIF analog output mode.</returns>
  public static string toString(PifAoMode analogOutputMode) {
    string ret = otcsdkPINVOKE.toString__SWIG_9((int)analogOutputMode);
    return ret;
  }

  /// <summary>Returns a string representation of the given PIF digital output mode.</summary>
  /// Use `pifDoModeToString()` in Python instead.
  /// <param name="digitalOutputMode"> for which a string representation is desired.</param> 
  /// <returns>string respresentation of the given PIF digital output mode.</returns>
  public static string toString(PifDoMode digitalOutputMode) {
    string ret = otcsdkPINVOKE.toString__SWIG_10((int)digitalOutputMode);
    return ret;
  }

  /// <summary>Returns a string representation of the given PIF fail safe mode.</summary>
  /// Use `pifFsModeToString()` in Python instead.
  /// <param name="failSafeMode"> for which a string representation is desired.</param> 
  /// <returns>string respresentation of the given PIF fail safe mode.</returns>
  public static string toString(PifFsMode failSafeMode) {
    string ret = otcsdkPINVOKE.toString__SWIG_11((int)failSafeMode);
    return ret;
  }

  /// <summary>Returns a string representation of the given PIF analog output mode.</summary>
  /// Use `pifAoOutputModeToString()` in Python instead.
  /// <param name="outputMode"> for which a string representation is desired.</param> 
  /// <returns>string respresentation of the given PIF analog output mode.</returns>
  public static string toString(PifAoOutputMode outputMode) {
    string ret = otcsdkPINVOKE.toString__SWIG_12((int)outputMode);
    return ret;
  }

}

}
