//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the available modes for PIF analog output channels.
public enum PifAoMode {
  ///  Off.
  Off,
  ///  The status of the shutter flag is output.
  FlagStatus,
  ///  Every time a new frame is capture a pulse is output.
  FrameSync,
  ///  A heart beat signal is provided that indicates whether the camera and SDK are working correctly.
  FailSafe,
  ///  The output value can be controlled by clients of the SDK.
  ExternalCommunication,
  ///  The set data point of a measurement field is output.
  MeasurementField,
  ///  The internal camera temperature is output.
  InternalTemperature
}

}
