//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the available modes for PIF digital input channels.
public enum PifDiMode {
  ///  Off.
  Off,
  ///  The flag is controlled by the input signal.
  FlagControl
}

}
