//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {
/// <summary>Encapsulates the configuration for a PIF fail safe channel.</summary>
/// For a detailed overview of all available modes and parameters please refer to the corresponding section in the documentation
/// of the [configuration file](#important-files-configuration-process-interface-fail-safe).

public class PifFsConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PifFsConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PifFsConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PifFsConfig obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PifFsConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otcsdkPINVOKE.delete_PifFsConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  ///  Constructor.
  public PifFsConfig() : this(otcsdkPINVOKE.new_PifFsConfig(), true) {
  }

  /// <summary>Creates a configuration for the PifFsMode::Off.</summary>
  /// <returns>configuration for the PifFsMode::Off.</returns>
  public static PifFsConfig createOff() {
    PifFsConfig ret = new PifFsConfig(otcsdkPINVOKE.PifFsConfig_createOff(), true);
    return ret;
  }

  /// <summary>Creates a configuration for the PifFsMode::On.</summary>
  /// <returns>configuration for the PifFsMode::On.</returns>
  public static PifFsConfig createOn() {
    PifFsConfig ret = new PifFsConfig(otcsdkPINVOKE.PifFsConfig_createOn(), true);
    return ret;
  }

  ///  Mode to be applied to the channel.
  public PifFsMode mode {
    set {
      otcsdkPINVOKE.PifFsConfig_mode_set(swigCPtr, (int)value);
    } 
    get {
      PifFsMode ret = (PifFsMode)otcsdkPINVOKE.PifFsConfig_mode_get(swigCPtr);
      return ret;
    } 
  }

}

}
